# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='dia',
            field=models.ForeignKey(default=1, max_length=25, on_delete=django.db.models.deletion.CASCADE, to='cadastro.dia', verbose_name='Dias Semana'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='periodo',
            field=models.ForeignKey(default=1, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='cadastro.periodo', verbose_name='Periodo'),
        ),
    ]
