# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20181215_0042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dia',
            new_name='dias',
        ),
    ]
