# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-20 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_auto_20190119_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='max',
            field=models.CharField(default=0, max_length=3, verbose_name='Qte max no mes'),
        ),
    ]
