# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-31 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_irmaos_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='irmaosLista',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cadastro.irmaos',),
        ),
    ]
