# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-26 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_auto_20190526_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='gr',
            field=models.CharField(choices=[('masculino', 'masculino'), ('feminino', 'feminino')], max_length=30, verbose_name='G\xeanero'),
        ),
    ]
