# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_auto_20190726_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='prioridade',
            field=models.BooleanField(default=False, verbose_name='Prioridade'),
        ),
    ]
