# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-01 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0033_auto_20190901_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='grupo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Grupo'),
        ),
    ]
