# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0035_auto_20190901_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='dianteira',
            field=models.CharField(blank=True, choices=[('Servo Ministerial', 'Servo Ministerial'), ('Anciao', 'Anciao')], max_length=20, null=True, verbose_name='Dianteira'),
        ),
    ]
