# Generated by Django 2.2.7 on 2019-11-30 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0039_irmaos_dtmodificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='dtModificado',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de modificacao'),
        ),
    ]
