# Generated by Django 2.2.7 on 2019-12-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0042_auto_20191213_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='designacao',
            new_name='designar',
        ),
    ]
