# Generated by Django 2.2.7 on 2019-12-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0043_auto_20191213_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designar',
            options={'verbose_name': 'Designação', 'verbose_name_plural': 'Designações'},
        ),
    ]
