# Generated by Django 2.2.7 on 2019-12-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0044_auto_20191213_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designar',
            name='dia_semana',
            field=models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terca-feira', 'Terca-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=25, verbose_name='Dia Semana'),
        ),
    ]
