# Generated by Django 2.2.7 on 2019-12-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0046_designar_ano'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='designar',
            new_name='designacao',
        ),
    ]
