# Generated by Django 2.2.7 on 2020-01-01 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0049_auto_20191231_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacao',
            name='ano',
            field=models.IntegerField(default=2020, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='irmaos',
            name='dtModificado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de modificacao'),
        ),
    ]
