# Generated by Django 2.2.7 on 2020-01-01 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0051_auto_20200101_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='dtModificado',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de modificacao'),
        ),
    ]
