# Generated by Django 2.2.7 on 2019-12-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='generate',
            new_name='consulta',
        ),
    ]
