# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-18 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(blank=True, max_length=25, null=True, verbose_name='mes')),
            ],
        ),
    ]
