# Generated by Django 2.2.7 on 2020-01-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=55, null=True, verbose_name='Titulo')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descricao')),
                ('data_inicial', models.DateTimeField(verbose_name='Data Inicial')),
                ('data_final', models.DateTimeField(verbose_name='Data Final')),
            ],
        ),
    ]
