# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20181214_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irmaos',
            options={'verbose_name': 'Irm\xe3o'},
        ),
        migrations.RemoveField(
            model_name='irmaos',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='irmaos',
            name='periodo',
        ),
        migrations.AddField(
            model_name='dia',
            name='irmao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.irmaos', verbose_name='Nome do irmao'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='bairro',
            field=models.CharField(default='Palmares', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='irmao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.irmaos', verbose_name='Nome do irmao'),
        ),
        migrations.AlterField(
            model_name='irmaos',
            name='cgcao',
            field=models.CharField(default='Palmares', max_length=90, verbose_name='Congrega\xe7\xe3o'),
        ),
    ]
