# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20181214_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='dia_semana',
            field=models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terca-feira', 'Terca-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=25, verbose_name='dia da semana'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.CharField(choices=[('Periodo 1', 'Periodo 1'), ('Periodo 2', 'Periodo 2'), ('Periodo 3', 'Periodo 3'), ('Periodo 4', 'Periodo 4')], max_length=80, verbose_name='Periodo'),
        ),
    ]
