# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20181214_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='irmao',
        ),
        migrations.AddField(
            model_name='periodo',
            name='dia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.dia', verbose_name='Dia'),
        ),
    ]
