# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-15 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20181214_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dia',
            name='p2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dia',
            name='p3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dia',
            name='p4',
            field=models.BooleanField(default=False),
        ),
    ]
