# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_auto_20181228_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias',
            name='adv',
            field=models.CharField(choices=[('Par', 'Par'), ('Impar', 'Impar'), ('Nulo', 'Nulo')], default='Nulo', max_length=6, null=True, verbose_name='Par/Impar'),
        ),
    ]
