# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_dias_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
