# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_dias_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='dia',
        ),
        migrations.AlterModelOptions(
            name='dias',
            options={'verbose_name': 'Dia', 'verbose_name_plural': 'Dia'},
        ),
        migrations.RemoveField(
            model_name='dias',
            name='habilitado',
        ),
        migrations.AddField(
            model_name='irmaos',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.DeleteModel(
            name='periodo',
        ),
    ]
