# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_auto_20190115_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dias',
            name='max',
        ),
        migrations.AddField(
            model_name='irmaos',
            name='max',
            field=models.CharField(max_length=3, null=True, verbose_name='Qte max no mes'),
        ),
    ]
