# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-28 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_auto_20190119_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='privilegio',
            field=models.CharField(choices=[('pioneiro', 'pioneiro'), ('publicador', 'publicador'), ('servo', 'servo ministerial'), ('anciao', 'anciao')], default='publicador', max_length=20, null=True, verbose_name='Privilegio'),
        ),
        migrations.AlterField(
            model_name='irmaos',
            name='max',
            field=models.CharField(default=6, max_length=3, verbose_name='Qte max no mes'),
        ),
    ]
