# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_auto_20190526_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias',
            name='preferencial',
            field=models.BooleanField(default=False, verbose_name='Preferencial'),
        ),
    ]
