# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_dias_preferencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='excecao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Excecao'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='trio',
            field=models.BooleanField(default=False, verbose_name='Trio'),
        ),
    ]
