# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_irmaos_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irmaos',
            name='prioridade',
        ),
    ]
