# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0029_auto_20190728_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='obs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observacao'),
        ),
    ]
