# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-31 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0030_auto_20190728_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='privilegio',
            field=models.CharField(choices=[('pioneiro regular', 'pioneiro regular'), ('pioneiro auxiliar', 'pioneiro auxiliar'), ('publicador', 'publicador'), ('servo', 'servo ministerial'), ('anciao', 'anciao')], default='publicador', max_length=20, null=True, verbose_name='Privilegio'),
        ),
    ]
