# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-01 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0031_auto_20190831_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='dianteira',
            field=models.CharField(choices=[('Servo Ministerial', 'Servo Ministerial'), ('Anciao', 'Anciao')], max_length=20, null=True, verbose_name='Dianteira'),
        ),
    ]
