# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0032_irmaos_dianteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='batismo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Batismo'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='telefone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telfone 1'),
        ),
        migrations.AddField(
            model_name='irmaos',
            name='telefone2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='irmaos',
            name='obs',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observacao'),
        ),
    ]
