# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0036_auto_20190901_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmaos',
            name='nm_completo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='irmaos',
            name='nm',
            field=models.CharField(max_length=55, verbose_name='Nome do irmao'),
        ),
        migrations.AlterField(
            model_name='irmaos',
            name='telefone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone 1'),
        ),
    ]
