# Generated by Django 2.2.7 on 2019-12-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0040_auto_20191130_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='designacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=25, verbose_name='mes')),
                ('dia_semana', models.CharField(max_length=25, verbose_name='Dia Semana')),
                ('dia_mes', models.IntegerField(max_length=25, verbose_name='Dia Mes')),
                ('p1', models.CharField(max_length=35, verbose_name='P1')),
                ('p1_1', models.CharField(max_length=35, verbose_name='P1_1')),
                ('p1_2', models.CharField(max_length=35, verbose_name='P1_2')),
                ('p2', models.CharField(max_length=35, verbose_name='P2')),
                ('p2_1', models.CharField(max_length=35, verbose_name='P2_1')),
                ('p3', models.CharField(max_length=35, verbose_name='P3')),
                ('p3_1', models.CharField(max_length=35, verbose_name='P3_1')),
                ('p4', models.CharField(max_length=35, verbose_name='P4')),
                ('p4_1', models.CharField(max_length=35, verbose_name='P4_1')),
                ('p5', models.CharField(max_length=35, verbose_name='P5')),
                ('p5_1', models.CharField(max_length=35, verbose_name='P5_1')),
            ],
            options={
                'verbose_name': 'Designação',
            },
        ),
        migrations.AlterModelOptions(
            name='irmaoslista',
            options={'verbose_name': 'Irmãos - listagem simple'},
        ),
    ]
