# Generated by Django 2.2.7 on 2019-12-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0045_auto_20191213_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='designar',
            name='ano',
            field=models.IntegerField(default=2019, verbose_name='Ano'),
        ),
    ]
