# Generated by Django 2.2.7 on 2019-12-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0047_auto_20191213_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacao',
            name='csrfmiddlewaretoken',
            field=models.CharField(default=1, max_length=80, verbose_name='P1'),
        ),
    ]
