# Generated by Django 2.2.7 on 2019-12-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0048_designacao_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irmaos',
            name='grupo',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Grupo'),
        ),
    ]
