# Generated by Django 2.2.7 on 2020-01-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0053_auto_20200101_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacao',
            name='p1',
            field=models.CharField(max_length=35, verbose_name='Periodo 1'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p1_1',
            field=models.CharField(max_length=35, verbose_name='Periodo 1'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p1_2',
            field=models.CharField(max_length=35, verbose_name='Periodo 1'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p2',
            field=models.CharField(max_length=35, verbose_name='Periodo 2'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p2_1',
            field=models.CharField(max_length=35, verbose_name='Periodo 2'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p3',
            field=models.CharField(max_length=35, verbose_name='Periodo 3'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p3_1',
            field=models.CharField(max_length=35, verbose_name='Periodo 3'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p4',
            field=models.CharField(max_length=35, verbose_name='Periodo 4'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p4_1',
            field=models.CharField(max_length=35, verbose_name='Periodo 4'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p5',
            field=models.CharField(max_length=35, verbose_name='Periodo 5'),
        ),
        migrations.AlterField(
            model_name='designacao',
            name='p5_1',
            field=models.CharField(max_length=35, verbose_name='Periodo 5'),
        ),
    ]
